apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp
    version: 2.7.03
spec:
  type: Nodeport
  ports:
  - port: 8080
    nodePort: 30003
    protocol: TCP
  selector:
    app: myapp
    version: 2.7.03